# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Chandar Research Lab
# email: your-email@example.com
description: ""
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  chandar-lab
youtube_channel: UCa885azMHaNWAEEVeJHTjHw
youtube_channel_name: chandar-lab
twitter_username: ChandarLab

# Build settings
encoding: utf-8
markdown: kramdown
theme: minima

plugins:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  - jekyll-datapage-generator

whitelist:
  - jekyll-redirect-from

languages: ["en", "fr"]
exclude_from_localizations: ["assets/images", "youtube.html"]

header_pages:
  - index.html
  - people.html
  - publications.html
  - theses.html
  - join.html
  - youtube.html

page_gen:
  - data: people
    template: profile
    name: name
    dir: people
  - data: alumni
    template: profile
    name: name
    dir: people
    filter: profile_page

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
